#!/usr/bin/env python3

import pyscreenshot as ImageGrab # image processing
import cv2                       # image processing
from PIL import Image            # image processing

import sys # for flags
import os  # for getting computer details

'''constant variables'''
MAX_X = os.system("xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x'  -f1")
MAX_Y = os.system("xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x'  -f2")


def main():

    argsList = sys.argv[1:] # first argv is the file name

    '''we should take a full screenshot by default so we can use it throughout'''

    screenshot_name = argsList.pop(0)

    # full screenshot
    full_screenshot_name = screenshot_name + "Full.png"
    screenshot_full = ImageGrab.grab()
    screenshot_full.save(full_screenshot_name)

    '''
    while len(argsList) > 0:

        currentArg = argsList.pop(0)

        if currentArg = '-cp' # [c]rop [p]ixel
            screenshot_crop = ImageGrab.grab(bbox=(10, 10, 500, 500))
            screenshot_crop.save(cropped_screenshot_name) # saving cropped screenshot
    
        screenshot_to_rotate = cv2.imread(full_screenshot_name)
        screenshot_rotate_90_clockwise = cv2.rotate(screenshot_to_rotate, cv2.ROTATE_90_CLOCKWISE)
        cv2.imwrite(rotated_screenshot_name, screenshot_rotate_90_clockwise) # saving rotated screenshot

        size = 1300,500
        to_resize = Image.open(full_screenshot_name)
        screenshot_resize = to_resize.resize(size, Image.ANTIALIAS)
        screenshot_resize.save(changed_resolution_screenshot_name) # saving changed resolution screenshot
    '''

if __name__ == "__main__":
    main()
